state.reviewCourse=state.reviewCourse||"All";
function reviewLessons(){return lessons.filter(x=>state.reviewCourse==="All"||x.course===state.reviewCourse)}
function reviewStats(id){return typeof lessonReflectionStats==="function"?lessonReflectionStats(id):null}
function reviewStandards(){const rows=window.FONTaineStandards?.courseStandards?.map(coverageRecord)||[];return rows.filter(x=>state.reviewCourse==="All"||x.course===state.reviewCourse)}
function reviewFiles(){return (typeof driveFiles!=="undefined"?driveFiles:[]).filter(x=>state.reviewCourse==="All"||x.course===state.reviewCourse||x.course==="Shared")}
function reviewData(){const scoped=reviewLessons();const reflected=scoped.map(lesson=>({lesson,stats:reviewStats(lesson.id)})).filter(x=>x.stats);const top=[...reflected].sort((a,b)=>b.stats.average-a.stats.average).slice(0,5);const revision=[...reflected].filter(x=>x.stats.priority!=="Low").sort((a,b)=>a.stats.average-b.stats.average).slice(0,8);const incomplete=scoped.filter(x=>x.status!=="Complete").sort((a,b)=>a.readinessScore-b.readinessScore);const standards=reviewStandards();const weak=standards.filter(x=>x.level!=="Strong").sort((a,b)=>a.score-b.score);const files=reviewFiles();const unused=files.filter(x=>!x.match?.lessons?.length||x.match.confidence<35);const duplicates=Object.entries(files.reduce((out,file)=>{if(file.duplicateGroup)(out[file.duplicateGroup]??=[]).push(file);return out},{})).filter(([,items])=>items.length>1);const readiness=scoped.length?Math.round(scoped.reduce((sum,x)=>sum+(x.readinessScore||0),0)/scoped.length):0;const rating=reflected.length?(reflected.reduce((sum,x)=>sum+x.stats.average,0)/reflected.length).toFixed(1):"—";return{scoped,top,revision,incomplete,weak,unused,duplicates,readiness,rating}}
function reviewLessonRow(item,mode){const lesson=item.lesson||item;const stats=item.stats;const detail=mode==="top"?`${stats.average.toFixed(1)}/5 across ${stats.count} reflection(s)`:mode==="revision"?`${stats.average.toFixed(1)}/5 • ${stats.priority} priority`:`${lesson.readinessScore}% ready`;return `<div class="review-row"><div class="review-row-main"><strong>${lesson.id} — ${lesson.title}</strong><span class="muted">${lesson.course} • ${detail}</span></div><div class="review-row-actions"><button class="btn secondary" onclick="openLesson('${lesson.id}')">Open</button></div></div>`}
function reviewStandardRow(row){return `<div class="review-row"><div class="review-row-main"><strong>${row.code} — ${row.title}</strong><span class="muted">${row.score}% coverage • ${row.level}</span></div><div class="review-row-actions"><button class="btn" onclick="go('Standards')">Review</button></div></div>`}
function reviewResourceRow(file){return `<div class="review-row"><div class="review-row-main"><strong>${file.title}</strong><span class="muted">${file.course} • ${file.type} • ${file.match?.confidence||0}% match</span></div><div class="review-row-actions"><a class="btn secondary" href="${file.url}" target="_blank" rel="noopener">Open Drive</a></div></div>`}
function reviewPanel(title,subtitle,body){return `<section class="card review-panel"><h2>${title}</h2><p class="muted">${subtitle}</p><div class="review-list">${body||'<div class="review-empty">No records found.</div>'}</div></section>`}
function annualReviewView(){const d=reviewData();return shell(`<div class="card annual-review-toolbar"><div><h2>Annual Curriculum Review</h2><p class="muted">Plan next year using lesson, standards, reflection, and Drive evidence.</p></div><div class="filters"><select onchange="state.reviewCourse=this.value;render()">${["All","SEM","Fashion","Entrepreneurship"].map(x=>`<option ${state.reviewCourse===x?"selected":""}>${x}</option>`).join("")}</select><button class="btn" onclick="go('Build Queue')">Improve Curriculum</button></div></div><div class="grid review-metrics"><section class="card span-3"><div class="metric">${d.scoped.length}</div><div class="muted">Lessons reviewed</div></section><section class="card span-3"><div class="metric">${d.readiness}%</div><div class="muted">Average readiness</div></section><section class="card span-3"><div class="metric">${d.rating}</div><div class="muted">Average rating</div></section><section class="card span-3"><div class="metric">${d.weak.length}</div><div class="muted">Standards priorities</div></section></div><div class="review-health">${reviewPanel("Highest-Rated Lessons","Based on saved reflections.",d.top.map(x=>reviewLessonRow(x,"top")).join(""))}${reviewPanel("Revision Priorities","Medium and high priorities.",d.revision.map(x=>reviewLessonRow(x,"revision")).join(""))}${reviewPanel("Readiness Gaps","Lowest-readiness lessons first.",d.incomplete.slice(0,8).map(x=>reviewLessonRow(x,"incomplete")).join(""))}${reviewPanel("Standards Needing Reinforcement","Weakest coverage first.",d.weak.slice(0,8).map(reviewStandardRow).join(""))}${reviewPanel("Unused or Unmatched Resources","Files without confident lesson matches.",d.unused.slice(0,8).map(reviewResourceRow).join(""))}${reviewPanel("Duplicate Review","Possible resource families to clean up.",d.duplicates.slice(0,8).map(([name,files])=>`<div class="review-row"><div class="review-row-main"><strong>${name}</strong><span class="muted">${files.length} possible versions</span></div><button class="btn" onclick="go('Google Drive')">Compare</button></div>`).join(""))}</div>`)}
if(!pages.includes("Annual Review"))pages.splice(pages.indexOf("Reflections")+1,0,"Annual Review");
const renderBeforeAnnualReview=render;render=function(){if(state.page==="Annual Review"){document.getElementById("app").outerHTML=`<div id="app">${annualReviewView()}</div>`;return;}renderBeforeAnnualReview();};
render();