window.FONTaineDriveInventory={scannedAt:"2026-07-11T23:40:00Z",source:"Connected Google Drive",files:[
{id:"1IBdOHLl9-8rrf9sSGFRcdWt7jEQI74XbHpsRLHX-Qyg",title:"SEM-001 - Course Launch, Classroom Systems, and Teamwork Stations",course:"SEM",type:"Document",url:"https://docs.google.com/document/d/1IBdOHLl9-8rrf9sSGFRcdWt7jEQI74XbHpsRLHX-Qyg",modified:"2026-06-30",lessonIds:["SEM-001"]},
{id:"1OdDDa0kpR56wiWe7PYunDQM-FedMnb9cBTtYS5IK-3A",title:"SEM-002 - DECA, Workplace Readiness, and Career Growth",course:"SEM",type:"Document",url:"https://docs.google.com/document/d/1OdDDa0kpR56wiWe7PYunDQM-FedMnb9cBTtYS5IK-3A",modified:"2026-06-30",lessonIds:["SEM-002"]},
{id:"1xH9W-bQTbwvy6x9-9_NevX3w8oN_mnXRjzXZPyLQNe0",title:"SEM-003 - What Is Marketing? Customers, Value, and Exchange",course:"SEM",type:"Document",url:"https://docs.google.com/document/d/1xH9W-bQTbwvy6x9-9_NevX3w8oN_mnXRjzXZPyLQNe0",modified:"2026-07-10",lessonIds:["SEM-003"]},
{id:"1dqHHa60ewDhcgJzpu-8qJxsgNUOW-F8wxCucMR0TUnQ",title:"SEM-004 - Marketing Functions in Sports and Entertainment",course:"SEM",type:"Document",url:"https://docs.google.com/document/d/1dqHHa60ewDhcgJzpu-8qJxsgNUOW-F8wxCucMR0TUnQ",modified:"2026-07-10",lessonIds:["SEM-004"]},
{id:"1q36VD_cTXJEZO7-GGqBOPHW5KOodbVK-CONyCbDYKZw",title:"FASH-001 - Course Launch, Fashion Identity, and Teamwork Stations",course:"Fashion",type:"Document",url:"https://docs.google.com/document/d/1q36VD_cTXJEZO7-GGqBOPHW5KOodbVK-CONyCbDYKZw",modified:"2026-06-30",lessonIds:["FASH-001"]},
{id:"17-gEpjUTXGbi_8xQxL8gk1FdFJ8U8qyvpgQphSTCaAM",title:"Fashion-002 - DECA, Workplace Readiness, and Fashion Career Pathways",course:"Fashion",type:"Document",url:"https://docs.google.com/document/d/17-gEpjUTXGbi_8xQxL8gk1FdFJ8U8qyvpgQphSTCaAM",modified:"2026-06-30",lessonIds:["FASH-002"]},
{id:"1Lo2SguD9BdxVGXahvaBMoRuWYdl66utFKrtuvbMrqlg",title:"FASH-003 - Fashion Cycle and Trends",course:"Fashion",type:"Document",url:"https://docs.google.com/document/d/1Lo2SguD9BdxVGXahvaBMoRuWYdl66utFKrtuvbMrqlg",modified:"2026-07-10",lessonIds:["FASH-003"]},
{id:"1bNd_d9yfuKMoS4mHkN4AMRyOxWsxUdfspTr3JSRTuN8",title:"FASH-004 - History of Fashion and Cultural Influence",course:"Fashion",type:"Document",url:"https://docs.google.com/document/d/1bNd_d9yfuKMoS4mHkN4AMRyOxWsxUdfspTr3JSRTuN8",modified:"2026-07-10",lessonIds:["FASH-004"]},
{id:"1FyHZjNPtAYd3uaFaMJpFXkoOkKJBk4nyy7WldnDv7OQ",title:"SEM - Pricing in Sports and Entertainment - Slideshow",course:"SEM",type:"Slides",url:"https://docs.google.com/presentation/d/1FyHZjNPtAYd3uaFaMJpFXkoOkKJBk4nyy7WldnDv7OQ",modified:"2026-06-24",lessonIds:[]},
{id:"1sSNYrAwCob37EFMI-zbm4y9iLHwLb1qFyDsv8hIMsxA",title:"SEM - Fast Casual Restaurants Lesson - Complete Slideshow",course:"SEM",type:"Slides",url:"https://docs.google.com/presentation/d/1sSNYrAwCob37EFMI-zbm4y9iLHwLb1qFyDsv8hIMsxA",modified:"2026-06-21",lessonIds:[],duplicateGroup:"fast-casual"},
{id:"1AHGgzpZHuwXJOoapDRppekR5AbdV2j0HT31y0HgBQuc",title:"SEM - Fast Food vs Fast Casual - Lesson Slideshow",course:"SEM",type:"Slides",url:"https://docs.google.com/presentation/d/1AHGgzpZHuwXJOoapDRppekR5AbdV2j0HT31y0HgBQuc",modified:"2026-06-21",lessonIds:[],duplicateGroup:"fast-casual"},
{id:"1guGWcMi9MJqN2IkPsgq5dASOdLF_mCNVv3r8XR9Gvb0",title:"SEM - Fast Food vs Fast Casual - Deep Dive Slideshow",course:"SEM",type:"Slides",url:"https://docs.google.com/presentation/d/1guGWcMi9MJqN2IkPsgq5dASOdLF_mCNVv3r8XR9Gvb0",modified:"2026-06-21",lessonIds:[],duplicateGroup:"fast-casual"},
{id:"1qbde40yZ_bv8sKIMfKl0U2qWvsZU5F6sLPfgxJtQpKU",title:"Fashion of Yesterday & Today (Condensed) Updated 2025",course:"Fashion",type:"Slides",url:"https://docs.google.com/presentation/d/1qbde40yZ_bv8sKIMfKl0U2qWvsZU5F6sLPfgxJtQpKU",modified:"2026-01-12",lessonIds:["FASH-003","FASH-004","FASH-005","FASH-006","FASH-007","FASH-008"]},
{id:"1oYnbimjN0DLLcnQLHZeDJXd5y1yH6IFvbDaef8IYGKw",title:"Fashion Marketing - Met Gala Top 10 Fashion Review - Slideshow",course:"Fashion",type:"Slides",url:"https://docs.google.com/presentation/d/1oYnbimjN0DLLcnQLHZeDJXd5y1yH6IFvbDaef8IYGKw",modified:"2026-06-21",lessonIds:[]},
{id:"1R1aXUWbyPvY_dUVFX_ve8BfLQH6lD8ZTVLu9IOnoGM0",title:"Copy of Met Gala Top 10: Fashion Review",course:"Fashion",type:"Slides",url:"https://docs.google.com/presentation/d/1R1aXUWbyPvY_dUVFX_ve8BfLQH6lD8ZTVLu9IOnoGM0",modified:"2026-05-29",lessonIds:[],duplicateGroup:"met-gala-top10"},
{id:"1Xm7CxxiE2EpnQNczc0VLpt5hnYaF_h4OGllRZgWcW8w",title:"Fontaine Teaching System - Curriculum Engine Dashboard",course:"Shared",type:"Spreadsheet",url:"https://docs.google.com/spreadsheets/d/1Xm7CxxiE2EpnQNczc0VLpt5hnYaF_h4OGllRZgWcW8w",modified:"2026-07-10",lessonIds:[]}
]};