window.HUB_CONFIG={id:"four-ps",title:"The 4Ps of Marketing",missions:[
{id:"4P-01",level:"Quick",entries:1,minutes:8,title:"P Spotter",brief:"Identify the Product, Price, Place, and Promotion decisions behind a real offer.",outcomes:["Recognize the 4Ps","Use specific evidence"],prompts:["Choose a real product, service, event, team, artist, or fashion item.","Identify one specific decision for Product, Price, Place, and Promotion.","Choose the strongest P and explain how it helps attract the target customer."]},
{id:"4P-02",level:"Quick",entries:1,minutes:10,title:"Wrong P Repair",brief:"Fix one marketing-mix decision that does not fit the customer.",outcomes:["Diagnose poor fit","Recommend a correction"],prompts:["Choose one mismatch: luxury shoes sold in a dollar store, children’s cereal promoted on LinkedIn, a student app priced at $500, or concert tickets available only by mail.","Identify the P with the clearest problem and explain why it does not fit the target market.","Repair that P and explain how the change improves customer value or access."]},
{id:"4P-03",level:"Quick",entries:1,minutes:10,title:"One Change Reaction",brief:"Predict how changing one P affects the other three.",outcomes:["See the mix as connected","Predict consequences"],prompts:["Choose a familiar product and describe its current marketing mix briefly.","Make one major change to Product, Price, Place, or Promotion.","Explain one adjustment that may now be needed in each of the other three Ps."]},
{id:"4P-04",level:"Skill",entries:2,minutes:18,title:"Product Upgrade Lab",brief:"Improve an ordinary product for a specific customer without adding random features.",outcomes:["Design customer value","Prioritize useful features"],prompts:["Choose an ordinary product and define a specific target customer.","List three customer needs or frustrations related to the product.","Create three product changes including features, design, packaging, service, or brand experience.","Rank the changes and defend which one creates the most customer value."]},
{id:"4P-05",level:"Skill",entries:2,minutes:20,title:"Price Decision Desk",brief:"Choose a price strategy based on customer value, competition, and business goals.",outcomes:["Select a pricing approach","Defend value"],prompts:["Choose or invent a product and describe the target customer and closest competitor.","Recommend a specific price and identify whether the strategy is premium, competitive, penetration, bundle, or another named approach.","Explain how customer value, competitor prices, and business goals support your choice.","Name one pricing risk and one way to reduce it."]},
{id:"4P-06",level:"Skill",entries:2,minutes:22,title:"Place Power Move",brief:"Design a distribution strategy that makes the offer convenient and believable.",outcomes:["Choose effective channels","Connect place to experience"],prompts:["Choose a product, service, ticket, or fashion item and define its target customer.","Select direct, retail, online, marketplace, event, subscription, or hybrid distribution channels.","Map how the customer discovers, buys, receives, and returns the offer.","Explain one tradeoff involving cost, control, speed, convenience, or brand image."]},
{id:"4P-07",level:"Skill",entries:2,minutes:22,title:"Promotion Mix Builder",brief:"Create a coordinated promotional plan instead of relying on one advertisement.",outcomes:["Coordinate communication tools","Set a measurable goal"],prompts:["Choose an offer and state one measurable promotional goal.","Select three promotional tools such as advertising, public relations, sales promotion, personal selling, direct marketing, social media, or sponsorship.","Describe the message, channel, and customer action for each tool.","Explain how the three tools support one another rather than repeating the same job."]},
{id:"4P-08",level:"Boss",entries:4,minutes:35,title:"Launch the Mystery Product",brief:"Build a complete, connected marketing mix for an unusual new offer.",outcomes:["Integrate all four Ps","Build customer consistency"],prompts:["Choose one offer: smart water bottle for athletes, mobile sneaker-cleaning service, virtual concert membership, sustainable school uniform, or late-night study café.","Define the primary target customer and customer problem.","Build the Product strategy with features, brand promise, packaging, and service.","Set the Price strategy with a specific price and value explanation.","Design the Place strategy and Promotion strategy with channels, message, and launch offer.","Explain how all four Ps reinforce one position in the customer’s mind."]},
{id:"4P-09",level:"Boss",entries:4,minutes:35,title:"Marketing Mix Rescue",brief:"Repair a launch where the four marketing decisions contradict one another.",outcomes:["Diagnose mix conflict","Build an integrated repair"],prompts:["Use this scenario: A premium eco-friendly jacket has weak materials, a bargain price, distribution through discount vending machines, and luxury magazine ads. Identify at least six contradictions or risks.","Define the most logical target customer and desired market position.","Redesign each of the four Ps with specific decisions.","Explain the order in which the company should make the changes and why.","Choose three measures that would show whether the repaired mix is working."]},
{id:"4P-10",level:"Boss",entries:4,minutes:38,title:"Head-to-Head Strategy",brief:"Compare two competitors and design a stronger 4Ps strategy for a challenger.",outcomes:["Analyze competitors","Create differentiation"],prompts:["Choose two competitors and compare their Product, Price, Place, and Promotion decisions.","Identify one strength and one weakness in each competitor’s marketing mix.","Define an underserved target customer or unmet need.","Create a challenger brand with a complete 4Ps strategy designed around that opportunity.","Write a positioning statement and explain why the challenger would be difficult to copy."]}
]};