const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const read=name=>fs.readFileSync(name,'utf8');
const files={
 source:read('mp2-source-data.js'),fashionSources:read('fashion-mp2-customer-service-sources.js'),marketingSources:read('entrepreneurship-mp2-marketing-sources.js'),ownershipSources:read('entrepreneurship-mp2-ownership-sources.js'),map:read('mp2-curriculum-map.js'),
 semPromotion:read('sem-mp2-promotion-packages.js'),semPromotionPatch:read('sem-mp2-promotion-quality-patch.js'),semSelling:read('sem-mp2-selling-packages.js'),semProfessional:read('sem-mp2-professional-skills-packages.js'),
 fashionPromotion:read('fashion-mp2-promotion-packages.js'),fashionPromotionPatch:read('fashion-mp2-promotion-quality-patch.js'),fashionSelling:read('fashion-mp2-selling-packages.js'),fashionSellingPatch:read('fashion-mp2-selling-quality-patch.js'),fashionCustomer:read('fashion-mp2-customer-service-packages.js'),fashionCustomerPatch:read('fashion-mp2-customer-service-quality-patch.js'),
 marketingA:read('entrepreneurship-mp2-marketing-packages-a.js'),marketingB:read('entrepreneurship-mp2-marketing-packages-b.js'),ownershipA:read('entrepreneurship-mp2-ownership-packages-a.js'),ownershipB:read('entrepreneurship-mp2-ownership-packages-b.js'),index:read('index.html')
};
const rows=[['SEM','8175','SEM'],['Fashion','8140','FASH'],['Entrepreneurship','9093','ENT']];
const lessons=rows.flatMap(([course,courseCode,prefix])=>Array.from({length:20},(_,index)=>({id:`${prefix}-${String(index+1).padStart(3,'0')}`,course,courseCode,title:`${course} MP1 ${index+1}`,unit:'MP1',unitId:'mp1',day:index+1,status:'Complete',markingPeriod:'MP1',standards:'MP1',duration:'45–60 minutes',components:['Lesson Plan','Learning Target','Agenda','Activity','Exit Ticket','Canvas Directions'],overview:'Complete',target:'I will learn.',success:'80% accuracy',agenda:[],bellRinger:'',miniLesson:'',activity:'',exitTicket:'',materials:[],differentiation:[],canvas:'Submit in Canvas. Earn at least 80% mastery.',notes:'',version:'Version 1'})));
const data={courses:rows.map(([title,code])=>({title,code})),units:{},lessonTitles:{},resources:[]};
const resources=[];const state={page:'Dashboard',selected:lessons[0],lessonTab:'Overview',search:'',course:'All',status:'All'};
const context={console,data,lessons,resources,state,CURRENT_DAY:8,window:null,FONTaineStandards:{courseStandards:[],wrsMappings:{}},FONTaineDriveInventory:{files:[]},shell:v=>v,badge:v=>v,openLesson(){},go(){},render(){},lessonView(){return'';},lessonList(){return'';},courses(){return'';},buildQueue(){return'';},dashboard(){return'';}};context.window=context;vm.createContext(context);
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}

test('ownership source and package JavaScript parse',()=>{new vm.Script(files.ownershipSources);new vm.Script(files.ownershipA);new vm.Script(files.ownershipB);});
test('index loads ownership source before app/map and packages after Marketing Principles',()=>{const source=files.index.indexOf('mp2-source-data.js'),ownershipSource=files.index.indexOf('entrepreneurship-mp2-ownership-sources.js'),app=files.index.indexOf('app.js'),map=files.index.indexOf('mp2-curriculum-map.js'),marketingB=files.index.indexOf('entrepreneurship-mp2-marketing-packages-b.js'),ownershipA=files.index.indexOf('entrepreneurship-mp2-ownership-packages-a.js'),ownershipB=files.index.indexOf('entrepreneurship-mp2-ownership-packages-b.js'),companions=files.index.indexOf('sem-mp2-companion-resources.js');assert.ok(source<ownershipSource&&ownershipSource<app&&app<map&&map<marketingB&&marketingB<ownershipA&&ownershipA<ownershipB&&ownershipB<companions);});
[files.source,files.fashionSources,files.marketingSources,files.ownershipSources,files.map,files.semPromotion,files.semPromotionPatch,files.semSelling,files.semProfessional,files.fashionPromotion,files.fashionPromotionPatch,files.fashionSelling,files.fashionSellingPatch,files.fashionCustomer,files.fashionCustomerPatch,files.marketingA,files.marketingB,files.ownershipA,files.ownershipB].forEach(code=>vm.runInContext(code,context));
const batch=lessons.filter(lesson=>/^ENT-0(29|30|31|32|33|34|35)$/.test(lesson.id));
const required=['overview','target','success','agenda','bellRinger','miniLesson','activity','exitTicket','materials','differentiation','canvas','standards','notes','version'];

test('builds exactly seven Entrepreneurship Business Ownership packages',()=>{assert.equal(batch.length,7);assert.equal(context.FONTaineEntrepreneurshipMP2OwnershipPackages.count,7);assert.deepEqual(Array.from(context.FONTaineEntrepreneurshipMP2OwnershipPackages.lessonIds),['ENT-029','ENT-030','ENT-031','ENT-032','ENT-033','ENT-034','ENT-035']);});
test('all seven packages are complete and follow Fontaine format',()=>{batch.forEach(lesson=>{assert.equal(lesson.status,'Complete');assert.equal(lesson.mapStatus,'Built');assert.match(lesson.target,/^I will /);assert.doesNotMatch(lesson.target,/Today/i);assert.match(lesson.success,/with at least 80% accuracy\.$/);assert.match(lesson.standards,/9093\.043/);assert.match(lesson.standards,/9093\.048-\.053/);assert.match(lesson.canvas,/Canvas/);assert.match(lesson.canvas,/80% mastery/);required.forEach(field=>assert.ok(Array.isArray(lesson[field])?lesson[field].length:String(lesson[field]||'').trim(),`${lesson.id} missing ${field}`));});});
test('verified ownership and startup legal-risk sources remain linked',()=>{['ENT-029','ENT-030','ENT-031','ENT-032','ENT-033','ENT-034'].forEach(id=>{const lesson=lessons.find(item=>item.id===id);assert.ok(lesson.sourceIds.includes('ent-ownership-notes'),`${id} missing ownership notes`);assert.ok(lesson.sourceIds.includes('ent-ownership-slides'),`${id} missing ownership slides`);});['ENT-034','ENT-035'].forEach(id=>assert.ok(lessons.find(item=>item.id===id).sourceIds.includes('ent-startup-legal-case')));assert.match(lessons.find(item=>item.id==='ENT-029').notes,/1oV6uakhX3qtIcztTuEu3CxDpY7ffcvF3p6emlLlvZk0/);assert.match(lessons.find(item=>item.id==='ENT-034').notes,/1VSlbHAt7eZfV6Dh-F5EN_LhdW_JO4Uo28t45i_Gy7rs/);});
test('ownership sequence covers comparison, agreements, entities, decision matrix, and legal-risk planning',()=>{assert.match(lessons.find(item=>item.id==='ENT-029').activity,/six-factor ownership comparison matrix/i);assert.match(lessons.find(item=>item.id==='ENT-030').activity,/Sole-Proprietor Readiness Checklist/i);assert.match(lessons.find(item=>item.id==='ENT-031').activity,/partnership term sheet/i);assert.match(lessons.find(item=>item.id==='ENT-032').activity,/LLC-versus-corporation comparison/i);assert.match(lessons.find(item=>item.id==='ENT-033').activity,/assign weights/i);assert.match(lessons.find(item=>item.id==='ENT-034').activity,/risk register/i);assert.match(lessons.find(item=>item.id==='ENT-034').activity,/30-day legal and risk action plan/i);assert.match(lessons.find(item=>item.id==='ENT-035').activity,/at least fifteen business-specific items/i);assert.match(lessons.find(item=>item.id==='ENT-035').activity,/three questions for professionals/i);});
test('55 MP2 lessons are complete and five Entrepreneurship lessons remain planned',()=>{const mp2=lessons.filter(item=>item.markingPeriod==='MP2');assert.equal(mp2.filter(item=>item.status==='Complete').length,55);assert.equal(mp2.filter(item=>item.status==='Planned').length,5);assert.equal(mp2.filter(item=>item.course==='Entrepreneurship'&&item.status==='Complete').length,15);});
console.log(`\n${passed} Entrepreneurship MP2 Business Ownership QA checks passed.`);