const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const read=name=>fs.readFileSync(name,'utf8');
const files={source:read('mp2-source-data.js'),fashionSources:read('fashion-mp2-customer-service-sources.js'),entSources:read('entrepreneurship-mp2-marketing-sources.js'),map:read('mp2-curriculum-map.js'),semPromotion:read('sem-mp2-promotion-packages.js'),semPromotionPatch:read('sem-mp2-promotion-quality-patch.js'),semSelling:read('sem-mp2-selling-packages.js'),semProfessional:read('sem-mp2-professional-skills-packages.js'),fashionPromotion:read('fashion-mp2-promotion-packages.js'),fashionPromotionPatch:read('fashion-mp2-promotion-quality-patch.js'),fashionSelling:read('fashion-mp2-selling-packages.js'),fashionSellingPatch:read('fashion-mp2-selling-quality-patch.js'),fashionCustomer:read('fashion-mp2-customer-service-packages.js'),fashionCustomerPatch:read('fashion-mp2-customer-service-quality-patch.js'),packagesA:read('entrepreneurship-mp2-marketing-packages-a.js'),packagesB:read('entrepreneurship-mp2-marketing-packages-b.js'),index:read('index.html')};
const rows=[['SEM','8175','SEM'],['Fashion','8140','FASH'],['Entrepreneurship','9093','ENT']];
const lessons=rows.flatMap(([course,courseCode,prefix])=>Array.from({length:20},(_,index)=>({id:`${prefix}-${String(index+1).padStart(3,'0')}`,course,courseCode,title:`${course} MP1 ${index+1}`,unit:'MP1',unitId:'mp1',day:index+1,status:'Complete',markingPeriod:'MP1',standards:'MP1',duration:'45–60 minutes',components:['Lesson Plan','Learning Target','Agenda','Activity','Exit Ticket','Canvas Directions'],overview:'Complete',target:'I will learn.',success:'80% accuracy',agenda:[],bellRinger:'',miniLesson:'',activity:'',exitTicket:'',materials:[],differentiation:[],canvas:'Submit in Canvas. Earn at least 80% mastery.',notes:'',version:'Version 1'})));
const data={courses:rows.map(([title,code])=>({title,code})),units:{},lessonTitles:{},resources:[]};const resources=[];const state={page:'Dashboard',selected:lessons[0],lessonTab:'Overview',search:'',course:'All',status:'All'};const context={console,data,lessons,resources,state,CURRENT_DAY:8,window:null,FONTaineStandards:{courseStandards:[],wrsMappings:{}},FONTaineDriveInventory:{files:[]},shell:v=>v,badge:v=>v,openLesson(){},go(){},render(){},lessonView(){return'';},lessonList(){return'';},courses(){return'';},buildQueue(){return'';},dashboard(){return'';}};context.window=context;vm.createContext(context);
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
test('Entrepreneurship marketing source and package files parse',()=>{new vm.Script(files.entSources);new vm.Script(files.packagesA);new vm.Script(files.packagesB);});
test('index loads Entrepreneurship source patch before app/map and packages after prior course builds',()=>{const source=files.index.indexOf('mp2-source-data.js'),entSources=files.index.indexOf('entrepreneurship-mp2-marketing-sources.js'),app=files.index.indexOf('app.js'),map=files.index.indexOf('mp2-curriculum-map.js'),fashion=files.index.indexOf('fashion-mp2-customer-service-packages.js'),a=files.index.indexOf('entrepreneurship-mp2-marketing-packages-a.js'),b=files.index.indexOf('entrepreneurship-mp2-marketing-packages-b.js'),companions=files.index.indexOf('sem-mp2-companion-resources.js');assert.ok(source<entSources&&entSources<app&&app<map&&map<fashion&&fashion<a&&a<b&&b<companions);});
[files.source,files.fashionSources,files.entSources,files.map,files.semPromotion,files.semPromotionPatch,files.semSelling,files.semProfessional,files.fashionPromotion,files.fashionPromotionPatch,files.fashionSelling,files.fashionSellingPatch,files.fashionCustomer,files.fashionCustomerPatch,files.packagesA,files.packagesB].forEach(code=>vm.runInContext(code,context));
const batch=lessons.filter(lesson=>/^ENT-02[1-8]$/.test(lesson.id));const required=['overview','target','success','agenda','bellRinger','miniLesson','activity','exitTicket','materials','differentiation','canvas','standards','notes','version'];
test('builds exactly eight Entrepreneurship Marketing Principles packages',()=>{assert.equal(batch.length,8);assert.equal(context.FONTaineEntrepreneurshipMP2MarketingPackages.count,8);assert.deepEqual(Array.from(context.FONTaineEntrepreneurshipMP2MarketingPackages.lessonIds),['ENT-021','ENT-022','ENT-023','ENT-024','ENT-025','ENT-026','ENT-027','ENT-028']);});
test('all eight packages are complete and follow Fontaine format',()=>{batch.forEach(lesson=>{assert.equal(lesson.status,'Complete');assert.equal(lesson.mapStatus,'Built');assert.match(lesson.target,/^I will /);assert.doesNotMatch(lesson.target,/Today/i);assert.match(lesson.success,/with at least 80% accuracy\.$/);assert.match(lesson.standards,/9093\.065-\.073/);assert.match(lesson.canvas,/Canvas/);assert.match(lesson.canvas,/80% mastery/);required.forEach(field=>assert.ok(Array.isArray(lesson[field])?lesson[field].length:String(lesson[field]||'').trim(),`${lesson.id} missing ${field}`));});});
test('verified promotional-mix and Business Reboot sources are linked',()=>{['ENT-021','ENT-022','ENT-023','ENT-024','ENT-025','ENT-026'].forEach(id=>assert.ok(lessons.find(item=>item.id===id).sourceIds.includes('ent-promo-slides')));assert.ok(lessons.find(item=>item.id==='ENT-025').sourceIds.includes('ent-promo-sort'));['ENT-027','ENT-028'].forEach(id=>{const lesson=lessons.find(item=>item.id===id);assert.ok(lesson.sourceIds.includes('ent-business-reboot'));assert.ok(lesson.sourceIds.includes('ent-business-reboot-plan'));});assert.match(lessons.find(item=>item.id==='ENT-025').notes,/1mnfGZhekTLegcr-VkntTw9n4zFPzTTOs0pDLuIjQITY/);assert.match(lessons.find(item=>item.id==='ENT-027').notes,/1zvvNKyQ-zaFfcl_VRjukfTyoduxSY1BUHWB5LTdztpQ/);});
test('marketing sequence covers promotional tools, sorting, launch planning, and reboot',()=>{assert.match(lessons.find(item=>item.id==='ENT-022').miniLesson,/advertising, sales promotion, public relations, direct marketing, and personal selling/i);assert.match(lessons.find(item=>item.id==='ENT-025').activity,/Scenario Sorting/i);assert.match(lessons.find(item=>item.id==='ENT-026').activity,/at least three coordinated promotional tools/i);assert.match(lessons.find(item=>item.id==='ENT-026').activity,/measurement dashboard/i);assert.match(lessons.find(item=>item.id==='ENT-027').activity,/root-cause analysis/i);assert.match(lessons.find(item=>item.id==='ENT-028').activity,/investor-style presentation/i);});
test('48 MP2 lessons are complete and 12 Entrepreneurship lessons remain planned',()=>{const mp2=lessons.filter(item=>item.markingPeriod==='MP2');assert.equal(mp2.filter(item=>item.status==='Complete').length,48);assert.equal(mp2.filter(item=>item.status==='Planned').length,12);assert.equal(mp2.filter(item=>item.course==='Entrepreneurship'&&item.status==='Complete').length,8);});
console.log(`\n${passed} Entrepreneurship MP2 Marketing Principles QA checks passed.`);