const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const read=name=>fs.readFileSync(name,'utf8');
const files={companion:read('companion-resources.js'),source:read('mp2-source-data.js'),sourcePatch:read('fashion-mp2-customer-service-sources.js'),map:read('mp2-curriculum-map.js'),semPromotion:read('sem-mp2-promotion-packages.js'),semPromotionPatch:read('sem-mp2-promotion-quality-patch.js'),semSelling:read('sem-mp2-selling-packages.js'),semProfessional:read('sem-mp2-professional-skills-packages.js'),fashionPromotion:read('fashion-mp2-promotion-packages.js'),fashionPromotionPatch:read('fashion-mp2-promotion-quality-patch.js'),fashionSelling:read('fashion-mp2-selling-packages.js'),fashionSellingPatch:read('fashion-mp2-selling-quality-patch.js'),fashionCustomer:read('fashion-mp2-customer-service-packages.js'),fashionCustomerPatch:read('fashion-mp2-customer-service-quality-patch.js'),semExtension:read('sem-mp2-companion-resources.js'),fashionExtension:read('fashion-mp2-companion-resources.js'),index:read('index.html')};
const rows=[['SEM','8175','SEM'],['Fashion','8140','FASH'],['Entrepreneurship','9093','ENT']];
const lessons=rows.flatMap(([course,courseCode,prefix])=>Array.from({length:20},(_,index)=>({id:`${prefix}-${String(index+1).padStart(3,'0')}`,course,courseCode,title:`${course} MP1 ${index+1}`,unit:'MP1',unitId:'mp1',day:index+1,status:'Complete',markingPeriod:'MP1',standards:'MP1',duration:'45–60 minutes',components:['Lesson Plan','Learning Target','Agenda','Activity','Exit Ticket','Canvas Directions'],overview:'Complete',target:'I will apply the lesson concept.',success:'I will complete the task with at least 80% accuracy.',agenda:['Review'],bellRinger:'Analyze a scenario.',miniLesson:'Review the concept.',activity:'Complete the application using evidence.',exitTicket:'Explain one decision.',materials:['Student organizer','Scoring rubric','Exit ticket'],differentiation:['Provide support.'],canvas:'Submit in Canvas. Earn at least 80% mastery.',notes:'Source-backed.',version:'Version 1'})));
const data={courses:rows.map(([title,code])=>({title,code})),units:{},lessonTitles:{},resources:[]};const resources=[];const state={page:'Dashboard',selected:lessons[0],lessonTab:'Overview',search:'',course:'All',status:'All'};
const context={console,data,lessons,resources,state,pages:['Dashboard','Resource Library'],CURRENT_DAY:8,window:null,FONTaineStandards:{courseStandards:[],wrsMappings:{}},FONTaineDriveInventory:{files:[]},shell:v=>v,badge:v=>v,openLesson(){},go(){},toast(){},render(){},lessonView(){return'';},lessonList(){return'';},courses(){return'';},buildQueue(){return'';},dashboard(){return'';},navigator:{clipboard:{writeText(){return Promise.resolve();}}},document:{getElementById(){return{outerHTML:''};},querySelector(){return null;}},setTimeout};context.window=context;vm.createContext(context);
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
test('Fashion companion extension parses',()=>new vm.Script(files.fashionExtension));
test('index loads companion extensions after completed packages and before progress',()=>{const base=files.index.indexOf('companion-resources.js'),map=files.index.indexOf('mp2-curriculum-map.js'),fashionPackages=files.index.indexOf('fashion-mp2-customer-service-packages.js'),sem=files.index.indexOf('sem-mp2-companion-resources.js'),fashion=files.index.indexOf('fashion-mp2-companion-resources.js'),progress=files.index.indexOf('mp2-build-progress.js');assert.ok(base<map&&map<fashionPackages&&fashionPackages<sem&&sem<fashion&&fashion<progress);});
vm.runInContext(files.companion,context);assert.equal(context.FONTaineCompanionAudit.generatedResources,300);vm.runInContext(files.source,context);vm.runInContext(files.sourcePatch,context);vm.runInContext(files.map,context);vm.runInContext(files.semPromotion,context);vm.runInContext(files.semPromotionPatch,context);vm.runInContext(files.semSelling,context);vm.runInContext(files.semProfessional,context);vm.runInContext(files.fashionPromotion,context);vm.runInContext(files.fashionPromotionPatch,context);vm.runInContext(files.fashionSelling,context);vm.runInContext(files.fashionSellingPatch,context);vm.runInContext(files.fashionCustomer,context);vm.runInContext(files.fashionCustomerPatch,context);vm.runInContext(files.semExtension,context);vm.runInContext(files.fashionExtension,context);
test('adds five generated resources for every completed Fashion MP2 lesson',()=>{const summary=context.FONTaineFashionMP2CompanionResources;assert.equal(summary.lessons,20);assert.equal(summary.generated,100);assert.equal(summary.verified,8);assert.equal(summary.extendedVerified,2);assert.equal(context.FONTaineCompanionAudit.totalLessons,100);assert.equal(context.FONTaineCompanionAudit.generatedResources,500);assert.equal(context.FONTaineCompanionResources.filter(item=>item.status==='Generated'&&/^FASH-0(2[1-9]|3\d|40)$/.test(item.lessonIds[0])).length,100);});
test('generated type counts reach 100 each without generated answer keys',()=>{['Student Organizer','Scoring Rubric','Exit Ticket','Quick Check','Teacher Scoring Guide'].forEach(type=>assert.equal(context.FONTaineCompanionResources.filter(item=>item.status==='Generated'&&item.type===type).length,100));assert.equal(context.FONTaineCompanionResources.filter(item=>item.status==='Generated'&&item.type==='Answer Key').length,0);assert.equal(context.FONTaineCompanionAudit.verifiedAnswerKeys,3);});
test('adds eight unique verified Fashion MP2 files and extends the existing review and key',()=>{assert.equal(context.FONTaineCompanionAudit.verifiedResources,25);const guide=context.FONTaineCompanionSources.verifiedSources.find(item=>item.fileId==='1W0icXY1Ehxm9vHGyQMG6bIS1k5X2yUA-nI64w6KXFfA');const key=context.FONTaineCompanionSources.verifiedSources.find(item=>item.fileId==='1j_C8eHAVxN2WQaoLpY0GFM_Oi38xARUIf6YHetEkUzA');[guide,key].forEach(item=>{assert.ok(item.lessonIds.includes('FASH-020'));assert.ok(item.lessonIds.includes('FASH-040'));});const fileIds=context.FONTaineCompanionSources.verifiedSources.map(item=>item.fileId);assert.equal(new Set(fileIds).size,fileIds.length);});
test('verified Fashion sources link promotion, selling, pop-up, clienteling, and retention lessons',()=>{const verified=context.FONTaineCompanionSources.verifiedSources;assert.deepEqual(Array.from(verified.find(item=>item.id==='verified-fashion-mp2-promo-sort').lessonIds),['FASH-024']);assert.ok(verified.find(item=>item.id==='verified-fashion-mp2-selling-scenarios').lessonIds.includes('FASH-033'));assert.ok(verified.find(item=>item.id==='verified-fashion-mp2-pop-up-brief').lessonIds.includes('FASH-039'));assert.ok(verified.find(item=>item.id==='verified-fashion-mp2-clienteling-notes').lessonIds.includes('FASH-036'));assert.deepEqual(Array.from(verified.find(item=>item.id==='verified-fashion-mp2-retention-notes').lessonIds),['FASH-037']);});
test('all Fashion MP2 lessons are complete before companion generation',()=>{const fashion=lessons.filter(item=>item.course==='Fashion'&&item.markingPeriod==='MP2');assert.equal(fashion.length,20);assert.ok(fashion.every(item=>item.status==='Complete'&&item.mapStatus==='Built'));});
console.log(`\n${passed} Fashion MP2 companion resource QA checks passed.`);